root: ./README.md
navigation:
  - title: "Wallet Development Kit (WDK)"
    file: README.md
  - title: "1 · Executive Summary & Overview"
    file: 1-executive-summary/README.md
  - title: "2 · Getting Started"
    file: 2-getting-started/README.md
  - title: "3 · Product Architecture & Core Concepts"
    file: 3-architecture/README.md
  - title: "4 · SDK Reference Documentation"
    file: 4-sdk-reference/README.md
  - title: "5 · Integration Patterns & Best Practices"
    file: 5-integration-patterns/README.md
  - title: "6 · Capabilities & Limitations"
    file: 6-capabilities/README.md
  - title: "7 · Code Examples & Tutorials"
    file: 7-examples/README.md
  - title: "8 · Troubleshooting & Support"
    file: 8-troubleshooting/README.md
  - title: "9 · Compliance & Legal"
    file: 9-compliance/README.md
  - title: "10 · Appendices"
    file: 10-appendices/README.md